name: Build Kotlin Multiplatform

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-kmp:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          android-sdk-path: '/home/anthony17/Android/Sdk'
      - name: Build KMP
        run: ./gradlew :composeApp:assemble

