name: Build Kotlin Multiplatform

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-kmp:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Create local.properties
        run: echo "sdk.dir=/home/anthony17/Android/Sdk" > local.properties
      - name: Build KMP
        run: ./gradlew :composeApp:assemble

