name: Build Kotlin Multiplatform

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-kmp:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Create local.properties
        run: echo "sdk.dir=/home/anthony17/Android/Sdk" > local.properties
      # Currently Raspberry Pi cannot build WASM due to ARM64 issues https://youtrack.jetbrains.com/issue/KT-70100/wasmJs-Target-Fails-to-Compile-on-ARM64-Linux
      - name: Build KMP
        run: ./gradlew build \
          -x compileDevelopmentExecutableKotlinWasmJs \
          -x compileDevelopmentExecutableKotlinWasmJsOptimize \
          -x compileKotlinWasmJs \
          -x compileProductionExecutableKotlinWasmJs \
          -x compileProductionExecutableKotlinWasmJsOptimize \
          -x compileTestDevelopmentExecutableKotlinWasmJs \
          -x compileTestDevelopmentExecutableKotlinWasmJsOptimize \
          -x compileTestKotlinWasmJs \
          -x compileTestProductionExecutableKotlinWasmJs \
          -x compileTestProductionExecutableKotlinWasmJsOptimize
