name: Build Kotlin Multiplatform

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  compile-kmp:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Create local.properties
        run: echo "sdk.dir=/home/anthony17/Android/Sdk" > local.properties
      # Currently Raspberry Pi cannot build WASM due to ARM64 issues https://youtrack.jetbrains.com/issue/KT-70100/wasmJs-Target-Fails-to-Compile-on-ARM64-Linux
      - name: Compile Desktop
        run: ./gradlew compileKotlinDesktop
      - name: Compile Android
        run: ./gradlew compileKotlinAndroid
      - name: Compile Web
        run: ./gradlew compileKotlinWasmJs
# Not sure this can be compiled on linux        
#./gradlew compileKotlinIos  # iOS target
